# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodDropApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodDropApp
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'

  # Optionally, include the Swift extensions if you're using Swift.
  pod 'FirebaseFirestoreSwift', '7.9.0-beta'
end

